name: Daily Automation

on:
  schedule:
    # This runs at 00:00 UTC every single day
    - cron: '0 0 * * *'
  workflow_dispatch: # This allows you to run it manually for testing

jobs:
  auto-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Daily Task
        run: |
          echo "Current Date: $(date)" > daily_log.txt
          echo "Automated daily update complete."

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily_log.txt
          git commit -m "Daily automated update [skip ci]" || echo "No changes to commit"
          git push
