name: Daily Contribution Bot
on:
  schedule:
    - cron: '0 0 * * *' # Midnight daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update log
        run: echo "Update on $(date)" > contribution_log.txt
      - name: Push change
        run: |
          git config --local user.email "your-github-email@example.com"
          git config --local user.name "sharmastar-01"
          git add contribution_log.txt
          git commit -m "Daily update"
          git push
